name: Animations Windows

on:
  push:
    branches: [feature/improves-animations]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    env:
      VERSION_NUMBER: 4.0.7
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17
        with:
          toolchain: nightly
      - uses: swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3
      - name: Test
        run: cargo test --locked --workspace
      - name: Build
        run: cargo build --locked --release --workspace
      - uses: actions/upload-artifact@v4
        with:
          name: glazewm-animations-windows-x64
          if-no-files-found: error
          path: |
            target/release/glazewm.exe
            target/release/glazewm-cli.exe
            target/release/glazewm-watcher.exe
